Do step 12. add the Order and OrderItem entity project
yurlis/book-store-app pull request #12
Opened 2024-06-27 16:16 UTC by yurlis

…eeded controller's endpoints.

2024-06-28 15:01 UTC, MAMentorFX requested changes

2024-06-28 15:01 UTC, MAMentorFX commented on src/main/java/com/bookstoreapp/controller/OrderController.java
> +        User user = (User) authentication.getPrincipal();
extract to local method

2024-06-28 15:01 UTC, MAMentorFX commented on src/main/java/com/bookstoreapp/mapper/OrderItemMapper.java
> +    @Mapping(target = "quantity", source = "quantity")
```suggestion
```

2024-06-28 15:01 UTC, MAMentorFX commented on src/main/java/com/bookstoreapp/mapper/OrderMapper.java
> +    @Mapping(target = "status", source = "status")
```suggestion
```

2024-06-28 15:01 UTC, MAMentorFX commented on src/main/java/com/bookstoreapp/service/OrderServiceImpl.java
> +    private EntityManager entityManager;
tell me the reason for this field here? I think it's redundant

2024-06-28 15:01 UTC, MAMentorFX commented on src/main/java/com/bookstoreapp/service/OrderServiceImpl.java
> +                .toList();
Mapstruct supports mapping collections from the box

2024-06-28 15:01 UTC, MAMentorFX commented on src/main/java/com/bookstoreapp/service/OrderServiceImpl.java
> +                .toList();
Mapstruct supports mapping collections from the box

2024-06-29 08:05 UTC, yurlis commented on src/main/java/com/bookstoreapp/service/OrderServiceImpl.java
> +    private EntityManager entityManager;
The search for a solution was difficult. We couldn't find a way to bind order_items. I forgot to delete it.

2024-06-30 11:27 UTC, okuzan requested changes

2024-06-30 11:27 UTC, okuzan commented on src/main/java/com/bookstoreapp/service/OrderServiceImpl.java
> +//                .toList();
don't forget to remove commented out code

2024-06-30 11:27 UTC, okuzan commented on src/main/java/com/bookstoreapp/model/Order.java
> +@SQLDelete(sql = "UPDATE books SET is_deleted = true WHERE id=?")
```suggestion
@SQLRestriction("is_deleted = FALSE")
@SQLDelete(sql = "UPDATE books SET is_deleted = TRUE WHERE id = ?")
```

2024-06-30 11:27 UTC, okuzan commented on src/main/java/com/bookstoreapp/service/OrderServiceImpl.java
> +                })
try to extract to a private method for clarity

2024-06-30 11:27 UTC, okuzan commented on src/main/java/com/bookstoreapp/service/OrderServiceImpl.java
> +        order.setTotal(BigDecimal.valueOf(0));
```suggestion
        order.setTotal(BigDecimal.ZERO);
```

2024-06-30 11:27 UTC, okuzan commented on src/main/java/com/bookstoreapp/service/OrderServiceImpl.java
> +                () -> new RuntimeException("Cannot find user by user id: " + userId)));
EntityNotFound

2024-06-30 11:27 UTC, okuzan commented on src/main/java/com/bookstoreapp/service/OrderServiceImpl.java
> +//                .toList();
same

2024-07-02 16:22 UTC, sarakhmen approved these changes

2024-07-03 09:36 UTC, merged