Do step 14 - Add tests for a Book functionality
yurlis/book-store-app pull request #14
Opened 2024-09-17 14:57 UTC by yurlis

2024-09-18 10:09 UTC, MentorMateAcademy requested changes

2024-09-18 10:09 UTC, MentorMateAcademy commented on src/test/java/com/bookstoreapp/controller/BookControllerIntegrationTest.java
> +import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
don`t use * in imports

2024-09-18 10:09 UTC, MentorMateAcademy commented on src/test/java/com/bookstoreapp/controller/BookControllerIntegrationTest.java
> +        assertNotNull(actual);
```suggestion
        BookDto actual = objectMapper.readValue(result.getResponse().getContentAsString(), BookDto.class);
        
                // Then
        assertNotNull(actual);
```

2024-09-18 10:09 UTC, MentorMateAcademy commented on src/test/java/com/bookstoreapp/controller/BookControllerIntegrationTest.java
> +
Extract to private build methods

2024-09-18 10:09 UTC, MentorMateAcademy commented on src/test/java/com/bookstoreapp/controller/BookControllerIntegrationTest.java
> +        // Then
```suggestion
        // when
```

2024-09-18 10:09 UTC, MentorMateAcademy commented on src/test/java/com/bookstoreapp/controller/BookControllerIntegrationTest.java
> +        // When
```suggestion
        // Then
```

2024-09-18 10:09 UTC, MentorMateAcademy commented on src/test/java/com/bookstoreapp/controller/CategoryControllerIntegrationTest.java
> +        CategoryDto actual = objectMapper.readValue(result.getResponse().getContentAsString(), CategoryDto.class);
//when part

2024-09-18 10:09 UTC, MentorMateAcademy commented on src/test/java/com/bookstoreapp/controller/CategoryControllerIntegrationTest.java
> +                .andReturn();
mock  it`s //given part

2024-09-18 10:09 UTC, MentorMateAcademy commented on src/test/java/com/bookstoreapp/service/BookServiceTest.java
> +                .setCategories(Set.of(1L));  // Використовуємо ID категорій
don`t need comments in code

2024-09-18 10:09 UTC, MentorMateAcademy commented on src/test/java/com/bookstoreapp/service/BookServiceTest.java
> +                .setCategoriesIds(Set.of(1L));
save values to constants and reuse it

2024-09-18 10:09 UTC, MentorMateAcademy commented on src/test/java/com/bookstoreapp/service/CategoryServiceTest.java
> +    private CategoryServiceImpl categoryService;
place after mocks

2024-09-18 11:31 UTC, yurlis commented on src/test/java/com/bookstoreapp/controller/CategoryControllerIntegrationTest.java
> +                .andReturn();
I I'm sorry, I didn't understand that comment. If you use MockBean for CategoryService, then it will entail redesigning the entire CategoryControllerIntegrationTest class. Because I use a populated database with database/categories/insert-categories.sql in the retrieval methods.

2024-09-19 13:04 UTC, sarakhmen requested changes
test reject

2024-09-20 17:53 UTC, okuzan approved these changes

2024-09-20 17:53 UTC, okuzan commented on src/test/resources/application.properties
> +# ????????? ??????? MockMvc (???? ???????? ????? MockMvc)
remove comments

2024-09-20 18:07 UTC, merged