Do step 15 - Add tests for a ShoppingCart functionality. Level Servic…
yurlis/book-store-app pull request #15
Opened 2024-09-21 20:50 UTC by yurlis

…e and Repository - ok. I tried doing with Mock Service and Repository levels, but nothing worked. Unfortunately.

2024-09-24 13:29 UTC, yurlis commented
![shopping-cart-coverage](https://github.com/user-attachments/assets/6fe65a65-61a2-4b9f-9f72-9e6aeeffbdbf)
Kind of code coverage is shown for the Shopping Cart, but I don't know why it doesn't show for the repository tests.

2024-09-24 14:30 UTC, Elena-Bruyako requested changes
Why there are several versions of ShopCartSertvice tests? 
When you test controller layer, you need to use integration tests only
Let's discuss in chat your implementation

2024-09-24 14:30 UTC, Elena-Bruyako commented on src/main/java/com/bookstoreapp/service/ShoppingCartServiceImpl.java
> +            BookAlreadyExistsException.supplier("Book already exists in the cart");
it's better to increase quantity of book in this case
what if user would like to add 2 books? ))

2024-09-24 14:30 UTC, Elena-Bruyako commented on src/main/java/com/bookstoreapp/repository/role/RoleRepository.java
> +    Role getRoleByRoleType(@Param("role_name") Role.RoleType roleType);
Why do you need this method?

2024-09-24 20:40 UTC, yurlis commented
![full-application-coverage](https://github.com/user-attachments/assets/45cc66ff-fd8e-484e-a0a8-62abbca582ef)
Test coverage of controller and service level classes

2024-09-26 06:45 UTC, liliia-ponomarenko requested changes
I answered your questions regarding Olena's comments in the discussion on the platform. So first let's come to a common decision and then make a request for a recheck.
I also see that in the new commit you added the findByEmail method to the service leyer and tested it, but I didn't find any use for this method, why is it needed?

2024-09-27 13:54 UTC, Elena-Bruyako requested changes

2024-09-27 13:54 UTC, Elena-Bruyako commented on src/test/java/com/bookstoreapp/controller/ShoppingCartControllerTest.java
> +public class ShoppingCartControllerTest {
unit test for controller still here, please remove it

2024-10-02 09:14 UTC, merged