Spring Boot Web Task 2 done.
yurlis/book-store-app pull request #2
Opened 2024-03-22 11:59 UTC by yurlis

But HINT recommendation i didn't use. Use pom.xml configuration from lessons video.

2024-03-22 14:10 UTC, kerrrusha requested changes

2024-03-22 14:10 UTC, kerrrusha commented on src/main/java/com/bookstoreapp/controller/BookController.java
> +@RequestMapping(value = "api/books")
extract `api/` to the application properties `server.servlet.context-path=/api` or somehow property in order not to duplicate it each time in each controller
```suggestion
@RequestMapping("/books")
```

2024-03-22 14:10 UTC, kerrrusha commented on src/main/java/com/bookstoreapp/model/Book.java
>  @Data
dont use data on entites as it cause bugs, use getter/setter instead

2024-03-22 14:10 UTC, kerrrusha commented on src/test/java/com/bookstoreapp/BookstoreApplicationTests.java
> +    }
redundant test, better remove it

2024-03-24 16:14 UTC, MAMentorFX approved these changes

2024-03-24 16:14 UTC, MAMentorFX commented on src/main/java/com/bookstoreapp/repository/BookDaoImpl.java
> +        try (EntityManager entityManager = entityManagerFactory.createEntityManager()) {
Should it have catch block?

2024-03-26 13:39 UTC, merged