Security block. First part. Add User entity
yurlis/book-store-app pull request #7
Opened 2024-04-04 18:39 UTC by yurlis

Add the required DTOs and mapper. Add AuthenticationController. Do data validation in the new DTO classes. Add FieldMatch annotation for match password and repeatPassword fields. Consider to handle the RegistrationException using the GlobalExceptionHandler

2024-04-04 20:23 UTC, MAMentorFX requested changes

2024-04-04 20:23 UTC, MAMentorFX commented on pom.xml
> +</project>
```suggestion
</project>

```

2024-04-04 20:23 UTC, MAMentorFX commented on src/main/java/com/bookstoreapp/validator/isbn/IsbnCustomValidator.java
>      /*
Remove comments please

2024-04-04 20:23 UTC, MAMentorFX commented on src/main/java/com/bookstoreapp/service/UserServiceImpl.java
> +    }
multiple calls to DB. Make it trascational

2024-04-04 20:23 UTC, MAMentorFX commented on src/main/java/com/bookstoreapp/dto/user/UserRegistrationRequestDto.java
> +//    @Length(min = 8, max = 35, message = "Password must be between 5 and 35 characters")
remove comments

2024-04-04 20:23 UTC, MAMentorFX commented on src/main/java/com/bookstoreapp/exception/RegistrationException.java
> +
```suggestion
```

2024-04-04 20:23 UTC, MAMentorFX commented on src/main/java/com/bookstoreapp/mapper/UserMapper.java
> +}
```suggestion
}

```

2024-04-04 20:23 UTC, MAMentorFX commented on src/main/java/com/bookstoreapp/repository/user/UserRepository.java
> +}
```suggestion
}

```

2024-04-04 20:23 UTC, MAMentorFX commented on src/main/java/com/bookstoreapp/repository/user/UserRepository.java
> +
```suggestion
```

2024-04-04 20:23 UTC, MAMentorFX commented on src/main/java/com/bookstoreapp/service/UserServiceImpl.java
> +        user.setShippingAddress(requestDto.getShippingAddress());
Use @MapStruct

2024-04-05 11:26 UTC, Rommelua requested changes

2024-04-05 11:26 UTC, Rommelua commented on src/main/java/com/bookstoreapp/validator/password/FieldMatchValidator.java
> +        }
```suggestion
            return Objects.equals(firstObj, secondObj);
```

2024-04-05 11:26 UTC, Rommelua commented on src/main/java/com/bookstoreapp/validator/password/PasswordCustomValidator.java
> +                && (password.length() >= 8) && (password.length() < 128);
magic numbers

2024-04-07 09:39 UTC, MAMentorFX requested changes

2024-04-07 09:39 UTC, MAMentorFX commented on src/main/java/com/bookstoreapp/mapper/UserMapper.java
> +    UserRegistrationResponseDto toUserResponse(User user);
In the future you may have more Dtos, not only Registration Response, so such naming is not clear, which Dto it returns

2024-04-07 09:39 UTC, MAMentorFX commented on src/main/java/com/bookstoreapp/service/UserServiceImpl.java
> +    }
You dont need to use toUserModel here. You have to use return value of findByEmail, so change isPresent to orElseThrow.

2024-04-07 09:39 UTC, MAMentorFX commented on src/main/java/com/bookstoreapp/validator/password/FieldMatchValidator.java
> +        Object secondObj = new BeanWrapperImpl(value).getPropertyValue(secondFieldName);
Does it actually require creation of two different BeanWrapperImpl objects?

2024-04-08 08:29 UTC, Vasul-Pankiv approved these changes

2024-04-08 09:44 UTC, merged